const cases = document.querySelector('#casos');
cases.prepend(document.querySelector('#presencial'));
cases.append(document.querySelector('#mailing'), document.querySelector('#autorizacoes'));
document.querySelector('#presencial .eyebrow').textContent='01 / Análise operacional';
document.querySelector('#autorizacoes .eyebrow').textContent='03 / Gestão de processos';
document.querySelector('.case-nav').innerHTML='<a href="#presencial">01 / Atendimento presencial</a><a href="#mailing">02 / Mailing de vendas</a><a href="#autorizacoes">03 / Autorizações</a>';
document.querySelector('#presencial .metric-groups h4').textContent='Atendimento';

// Recortes inteiramente fictícios, coerentes entre os indicadores do mesmo conjunto.
const months=[
 {month:'Jan',emitted:4200,attended:3780,within:3024,tma:12,wait:11},
 {month:'Fev',emitted:4600,attended:4000,within:2800,tma:15,wait:16},
 {month:'Mar',emitted:4400,attended:4000,within:3400,tma:10,wait:8},
 {month:'Abr',emitted:4800,attended:4500,within:4050,tma:9,wait:6},
];
function table(head,rows){return `<div class="demo-table"><table><thead><tr>${head.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function horizontal(title,rows,unit=''){
 const max=Math.max(...rows.map(r=>r[1]));
 return `<figure class="horizontal-chart"><figcaption>${title}</figcaption>${rows.map(r=>`<div class="bar-row"><span>${r[0]}</span><div><i style="width:${r[1]/max*100}%"></i></div><strong>${r[1]}${unit}</strong></div>`).join('')}</figure>`;
}
function line(title,labels,values,unit='',domain){
 const max=domain||Math.ceil(Math.max(...values)*1.1);const points=values.map((v,i)=>`${65+i*(450/(values.length-1))},${205-v/max*155}`).join(' ');
 return `<figure class="trend-chart"><figcaption>${title}</figcaption><svg viewBox="0 0 580 250" role="img" aria-label="${title}: ${values.map((v,i)=>labels[i]+' '+v+unit).join(', ')}"><line x1="55" y1="205" x2="530" y2="205" stroke="#666"/><text x="40" y="209">0</text><text x="28" y="54">${max}${unit}</text><polyline points="${points}" fill="none" stroke="#fa823e" stroke-width="3"/>${values.map((v,i)=>{const x=65+i*450/(values.length-1),y=205-v/max*155;return `<circle cx="${x}" cy="${y}" r="4" fill="#e8ceb6"/><text x="${x}" y="${y-12}" text-anchor="middle">${v}${unit}</text><text x="${x}" y="230" text-anchor="middle">${labels[i]}</text>`;}).join('')}</svg></figure>`;
}
function section(id,title,html){document.querySelector('#'+id+' .demo').insertAdjacentHTML('beforeend',`<section class="expanded-view"><h4>${title}</h4>${html}</section>`);}
section('presencial','Visão mês a mês',`<p>O mesmo recorte mensal sustenta o volume, o abandono e o nível de serviço abaixo. Todos os valores são fictícios.</p><div class="chart-grid">${line('Senhas emitidas',months.map(m=>m.month),months.map(m=>m.emitted))}${line('Nível de serviço',months.map(m=>m.month),months.map(m=>m.within/m.attended*100),'%',100)}</div>${table(['Mês','Emitidas','Atendidas','Abandonadas','Dentro da meta','NS*','TMA','Espera'],months.map(m=>[m.month,m.emitted,m.attended,m.emitted-m.attended,m.within,(m.within/m.attended*100).toFixed(0)+'%',m.tma+' min',m.wait+' min']))}<p class="reading">* Definição fictícia: atendidas com espera de até 15 minutos ÷ atendidas. Fevereiro combina mais demanda, TMA maior e NS menor; é uma pista para investigação, não prova de causalidade. Em abril, 4.050 de 4.500 atendidas ficaram dentro da meta (90%).</p>`);
const heat=[[30,55,70,60,35],[35,60,85,75,45],[28,50,65,58,32],[40,65,80,70,42],[25,45,55,48,30]];
section('presencial','Quando a demanda se concentra',`<p>Mapa de calor de uma semana ilustrativa, independente do recorte mensal. Cada célula representa senhas emitidas.</p><div class="demo-table"><table class="heatmap"><thead><tr><th>Dia / hora</th>${['08h','09h','10h','11h','12h'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${heat.map((r,i)=>`<tr><th>${['Seg','Ter','Qua','Qui','Sex'][i]}</th>${r.map(v=>`<td style="background:rgba(250,130,62,${.12+v/85*.65})">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="reading">Cores mais intensas indicam maior volume. Terça às 10h concentra 85 senhas neste exemplo; esse recorte ajuda a discutir distribuição de escala.</p>`);
section('presencial','Tipos de fila, abandonos e pessoas',`<p>Recortes fictícios e independentes. Os nomes de operadores e as categorias de fila abaixo são ilustrativos.</p><div class="chart-grid">${horizontal('Senhas por tipo de fila',[['Geral',620],['Prioritária',280],['Agendada',100]])}${horizontal('Motivos de abandono',[['Desistência durante espera',42],['Ausência na chamada',25],['Outros motivos',13]])}</div>${table(['Operador fictício','Atendimentos','TMA','Tempo ocioso observado'],[['Pessoa A',80,'9 min','32 min'],['Pessoa B',68,'12 min','18 min'],['Pessoa C',75,'10 min','25 min']])}<p class="reading">Comparar pessoas exige considerar complexidade, perfil da fila, jornada e qualidade. Um TMA menor não determina sozinho quem atende melhor; ociosidade também depende da chegada e distribuição de demanda.</p>`);

const authorMonths=[['Jan',600,580,80,100],['Fev',660,650,100,110],['Mar',700,720,110,90],['Abr',680,700,90,70]];
section('autorizacoes','Visão gerencial: demanda e capacidade',`<p>Exemplo de acompanhamento agregado do App e dos grupos, inspirado nas visões gerencial, operacional e de capacidade do arquivo. Não é uma reprodução das telas originais.</p><div class="chart-grid">${line('Entrantes por mês',authorMonths.map(r=>r[0]),authorMonths.map(r=>r[1]))}${line('Backlog ao fim do mês',authorMonths.map(r=>r[0]),authorMonths.map(r=>r[4]))}</div>${table(['Mês','Entrantes','Finalizadas','Backlog inicial','Backlog final'],authorMonths)}<p class="reading">Cada mês usa backlog inicial + entradas − finalizações. O saldo final de um mês é o inicial do seguinte. Decisões dos grupos não são somadas às finalizações do App.</p>${horizontal('Capacidade mensal estimada × entrada de abril',[['Capacidade estimada',720],['Entrantes',680]])}<p class="reading">Estimativa fictícia: 6 pessoas × 20 dias × 360 minutos úteis/dia ÷ 60 minutos médios de esforço = 720 requisições. Esforço produtivo é diferente do tempo decorrido de uma requisição, que pode incluir espera. A conta simplifica o processo para explicar a análise de capacidade.</p>`);
section('autorizacoes','Visão dos grupos e dos prazos',`<div class="chart-grid">${horizontal('Requisições nos grupos — fotografia fictícia',[['Grupo A',32],['Grupo B',24],['Grupo C',14]])}${horizontal('Motivos de glosa — amostra fictícia',[['Documentação',18],['Carência',12],['Plano não apto',9],['Outros',6]])}</div>${table(['Grupo fictício','Pendentes','Tempo médio no grupo','Aguardando ação do grupo'],[['Grupo A',32,'18h',20],['Grupo B',24,'30h',15],['Grupo C',14,'22h',8]])}<p class="reading">O status de auditoria indica passagem pela análise complementar. Para o backlog acionável, é preciso distinguir o que aguarda ação do grupo do que depende de documentação ou de outra etapa.</p>${horizontal('Idade das pendências — recorte de 70 solicitações',[['Até 24h',24],['24–48h',20],['48–72h',16],['Mais de 72h',10]])}<p class="reading">As faixas são apenas ilustrativas. Não representam prazos da ANS; os limites aplicáveis precisam ser definidos por tipo de solicitação e regra vigente.</p>`);
section('autorizacoes','Produtividade e regimes de trabalho',`${table(['Recorte fictício','Pessoas','Horas produtivas','Tratativas','Tratativas/hora'],[['Remoto',3,900,450,'0,50'],['Presencial',3,900,468,'0,52']])}${horizontal('Tratativas por pessoa — recorte independente',[['Pessoa A',156],['Pessoa B',142],['Pessoa C',138]])}<p class="reading">Tratativas representam ações e podem ocorrer mais de uma vez na mesma requisição. Não equivalem às finalizações. A comparação entre remoto e presencial exige considerar horas disponíveis e complexidade dos casos, sem atribuir desempenho apenas ao regime de trabalho.</p>`);

const queryContainer=document.querySelector('#mailing .demo');
queryContainer.insertAdjacentHTML('beforeend',`<details class="full-query"><summary>Ver query completa do mailing</summary><p>Três consultas: cabeçalho/layout, tratamento de contatos e montagem da base final. O endereço do SharePoint foi ocultado; nomes de campos e regras foram preservados. Nenhum registro de cliente está incluído. A consulta de retornos é um fluxo separado e não está neste bloco.</p><pre tabindex="0" aria-label="Consultas completas do mailing em código M"><code>Carregando código…</code></pre><a class="text-button" href="./assets/mailing-query.m" download>Baixar código M →</a></details>`);
const fullQuery=document.querySelector('.full-query');
fullQuery.addEventListener('toggle',async()=>{
 if(!fullQuery.open||fullQuery.dataset.loaded)return;
 try{const response=await fetch('./assets/mailing-query.m');if(!response.ok)throw Error();fullQuery.querySelector('code').textContent=await response.text();fullQuery.dataset.loaded='true';}
 catch{fullQuery.querySelector('code').textContent='Não foi possível carregar o código. Use o link de download abaixo.';}
});
